services:
  backend:
    build:
      context: .
      dockerfile: DockerfileDev
    container_name: chatgogo-backend-dev
    restart: unless-stopped
    volumes:
      - .:/app # live-reload
      - air_tmp:/app/tmp
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      GIN_MODE: debug
      DB_HOST: "postgres"
      DB_PORT: "5432"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}

    command: ["air", "-c", ".air.toml"]

  postgres:
    image: postgres:18.0-alpine3.22
    container_name: chatgogo-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.0.4-alpine
    container_name: chatgogo-redis-dev
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  air_tmp:
